spring.application.name=VotingCalc
spring.datasource.url=jdbc:mysql://localhost:3306/votingage
spring.datasource.username=root
spring.datasource.password=amrutha@072005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true